name: Build Desktop App
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install Rust build toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        run: npm ci
      - name: build app
        run: npm run build
      - name: build tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'LofiPad v__VERSION__'
          releaseBody: 'See the assets below to download the latest version of LofiPad.'
          releaseDraft: true
          prerelease: false
